apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-leak-detector
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kube-leak-detector
          restartPolicy: OnFailure
          containers:
          - name: kube-leak-detector
            image: kube-leak-detector:local
            imagePullPolicy: IfNotPresent
            env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: leak-detector-webhooks
                  key: slack
            - name: TEAMS_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: leak-detector-webhooks
                  key: teams
